[general]
import = ["~/hhendrikk.dots/alacritty/themes/gruvbox_material_hard_dark.toml"]

[window]
opacity = 0.95
decorations = "none"
startup_mode = "Maximized"
padding = { x = 3, y = 3 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 11

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
